### ISSUE TITLE
ModuleNotFoundError: No module named 'dna_viewer'

### ISSUE THREAD

**Issue by brycelynch** [EpicGames/MetaHuman-DNA-Calibration#5]
This isn't an issue but trying to figure out why I'm getting this error when running dna_viewer_run_in_maya.py

```
# Error: No module named 'dna_viewer'
# Traceback (most recent call last):
#   File "<maya console>", line 49, in <module>
#   File "C:\Program Files\Autodesk\Maya2022\Python37\lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
#     return original_import(name, *args, **kwargs)
# ModuleNotFoundError: No module named 'dna_viewer' # 
```

**Comment by smilicev** [comment]
There is a problem with your `ROOT_DIR` variable value in your script.
This should be if you use mayapy interpreter in console application 

`ROOT_DIR = f"{ospath.dirname(ospath.abspath(__file__))}/..".replace("\\", "/")` 

But in your case, because you are using this example in Maya your line should be:

`ROOT_DIR = r"c:\MetaHuman-DNA-Calibration".replace("\\", "/")` 

or simpler 

`ROOT_DIR = "c:/MetaHuman-DNA-Calibration"`

If `c:/MetaHuman-DNA-Calibration` is location where you cloned this repo.

Here is where [documentation link](https://github.com/EpicGames/MetaHuman-DNA-Calibration#notes).

**Comment by brycelynch** [comment]
Great, thank you.  That worked and the documentation is excellent.  :)

**Comment by smilicev** [comment]
Great! Thanks.
