### ISSUE TITLE
python interpreter _py3dna import error

### ISSUE THREAD

**Issue by cysoo23** [EpicGames/MetaHuman-DNA-Calibration#56]
When attempting to run dna_demo.py from the Python interpreter, I included the environment setup code block at the beginning of the script. Unfortunately, I encountered an "ImportError: DLL load failed while importing _py3dna:" error message. How can I solve this?

**Comment by n0phx** [comment]
This could be due to the restrictions introduced in Python 3.8 and upwards, which require the usage of `os.add_dll_directory` . With the latest release of MetaHuman-DNA-Calibration, we have added some fallback paths which will automatically invoke add_dll_directory with the paths present on `PATH`, making it compatible with the earlier behavior. Please try again with the latest release.

**Comment by kalebzaki4** [comment]
The "ImportError: DLL load failed while importing _py3dna" error message indicates that Python is having trouble loading a dynamic link library (DLL) associated with the `dna` module. Here are several steps you can take to troubleshoot and resolve this issue:

### 1. **Verify Environment Setup:**
Ensure that your environment is correctly set up according to the instructions in the `README.md` file. Check that:
   - All required dependencies are installed.
   - The correct version of Python (usually specified in the documentation) is being used.
   - Any necessary environment variables are set.

### 2. **Check for Missing Dependencies:**
The `dna` module may rely on other DLLs that need to be present in your environment. Make sure that all dependencies are correctly installed. You can use tools like **Dependency Walker** (for Windows) to see if there are any missing DLLs required by `_py3dna`.

### 3. **Install Required Packages:**
If the `dna` module is a third-party package, ensure it’s correctly installed in your environment. You can try reinstalling it with:
```bash
pip uninstall dna
pip install dna  # Or the specific package command as required
```

### 4. **Use the Correct Python Interpreter:**
Make sure that you're using the same Python interpreter that is set up with your environment and has access to the `dna` module. Sometimes, using multiple Python installations can cause conflicts.

### 5. **Running from Maya Script Editor:**
Since you mentioned previously that the script is intended to be run from the Maya Script Editor, ensure you are using the Maya Python interpreter instead of a standalone Python interpreter. If you're running the script from the command line, use the Maya's built-in Python, like this:
```bash
mayapy dna_demo.py
```

### 6. **Check for Compatibility Issues:**
Ensure that the `dna` module is compatible with the version of Python you are using. Sometimes, specific modules may not work correctly with certain Python versions, especially if there are binary dependencies involved.

### 7. **Inspect the `_py3dna` Module:**
If you have access to the source code for the `dna` module, examine the `_py3dna` file for any specific initialization code that may be failing. This might provide insights into what is going wrong.

### 8. **Review Documentation or Contact Support:**
Check the documentation for any additional setup steps or troubleshooting tips. If the problem persists, consider reaching out to the maintainers or community for the `dna` module for more specific support.

By following these steps, you should be able to identify the cause of the "ImportError: DLL load failed" error and work towards a solution. If you find specific DLLs are missing, you may need to locate and install those dependencies to resolve the issue.
